### ISSUE TITLE
Useability when 'play' selected in viewer window

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#1] opened 2022-05-10 10:56 UTC
If play is selected in viewer window then the whole Naperi user interface can become unresponsive when certain view options are selected (xcorr and spectrum for example) because these are recalculated for each step in the play sequence.  Recalculation of xcorr when stepping in phase is not required as all xcorr images are returned in a single call to the processor class.  Stepping in 'phase' to see the different carriers is not strictly correct - hexsim has 7 phases but only 3 carriers.

**Comment by andreabassi78** [comment] 2022-05-11 11:35
I have reproduced the issue, it happens with large images when `xcorr`/`spectrum` computation gets long. I would skip the calculation if the viewer is in play mode. How does this sound?
For the problem of stepping the phase, the correct solution is to add a new spinbox with the desired carrier. Not done before to keep the interface simpler. I could add this to version >0.06. Let's keep the issue open until then

**Comment by pptman** [comment] 2022-05-11 12:37
It does seem quite useful to be able to scan through a stack and look at what the xcorr does.  Also it is useful to be able to be able to cycle through the different carriers in xcorr, but how mech recalculation is being done when using the "phase" play button?  I'm afraid I don't understand enough about the napari viewer yet to work out what is going on.  Is there a good place to find documentation?

**Comment by andreabassi78** [comment] 2022-05-12 07:55
I could find documentation on this and on the properties of the play button. I'll look into the class and eventually ask help.

**Comment by andreabassi78** [comment] 2022-05-20 08:26
I have found a reference to the play button[ here](https://github.com/napari/napari/blob/579a6f70cba833111ad4af728947192ceac5b418/napari/_qt/qt_dims_slider.py#L28).
Not sure how to set the play button yet but I asked for help on [imagesc](https://forum.image.sc/t/play-button-properties/67295)

Once this will be clearer, we should decide whether to stop the xcorr/spectrum calculation when play is selected, or use other strategies

**Comment by andreabassi78** [comment] 2022-05-20 16:01
Thanks to  the very useful responses in [imagesc ](https://forum.image.sc/t/play-button-properties/67295/2)I learned that the play button is currently private.

The suggestion was then to debounce the play button. In practice the on_step_change method is called only [every 250ms](https://github.com/andreabassi78/napari-sim-processor/blob/1ea11dd2131d2587b5c6100569f1d879dc2c5c59/src/napari_sim_processor/_sim_widget.py#L308), which seems avoiding unresponsiveness when xcorr/spetrum/calibration are continuously processed.

The downside is that you can have a 250ms delay in visualizing xcorr/spectrum even when the processing is very fast.

It seems to me to be a reasonable fix, maybe the time could be reduced to 100-200ms. I'll test it further next week and if there are no further comments I'll close the issue.

**Comment by andreabassi78** [comment] 2022-05-21 14:53
The timeout can nicely be set. It is [now set by the](https://github.com/andreabassi78/napari-sim-processor/blob/86cc37aac422e06ce16e5eac7677d1cdb6532c81/src/napari_sim_processor/_sim_widget.py#L320) execution time of the xcorr/spectrum calculation 
I am closing the issue.

**Comment by pptman** [comment] 2022-05-23 08:52
Hi @andreabassi78 , I am not sure that this totally fixes the issue.  The main problem seems to be with plotting either the eta circles or the carrier circles.  When I select play (on z, phase or angle) with either of these selected then the frame rate slows and the UI becomes unresponsive.  By comparison, with just xcorr selected then the frame rate is fast and the UI is responsive, so it is not xcorr that is causing the problem.  I am not sure where the hold-up is in the code when plotting circles, but I will keep looking.

The new UI interface element is useful to show bands.  It is a bit slightly confusing in that when looking at 4 angle 3 phase SIM data then you might expect the angle bar to perform this function, including its play button.  However with hexSIM data there is of course no angle bar and the new element is indeed needed.  I think we need think about this one a bit more, but it works better for now.

**Comment by andreabassi78** [comment] 2022-05-23 10:57
Ok, this makes me think that we could try to debounce the individual functions (show_spectrum, show_xcorr, show_carriers), and yes, plotting the circles is time-consuming (up to 200ms in my PC).
I will try this now, and in the meantime I will reopen the issue

**Comment by pptman** [comment] 2022-05-23 11:04
I don't think that it is all about debouncing the functions.  There seem to be several issues that are slowing things up including:
1. Calling some routines such as show_eta() and show_carrier() several times for each step as these are called by other routines that are being called such as show_xcorr(), show_spectrum() and show_wiener().
2. Raising layers to the top of the pile has a time penalty and this is happening a lot.  Maybe we should leave the layers in place when calling an update.  This is the default behaviour for image layers that are recalculated and being played automatically by napari.
3. Plotting circles in two calls seems to make show_eta() slow, especially as each call rearranges the layers again.

**Comment by andreabassi78** [comment] 2022-05-23 11:25
Agree, maybe a general function that shows everything (that is selected) would work better. I tried something similar in the past, but then I gave up. I need to think about that for a while, I'll look at this in a couple of days, then.

**Comment by andreabassi78** [comment] 2022-05-24 06:51
1) I made some changes to avoid calling the functions twice or more. It helps but it does not solve completely the problem.
2) Raising layers to the top takes 5 ms. I left it in some cases
3) Showing shapes takes time: 120ms for creating the shape layer, 90ms for updating it.  It is run twice in show_eta. I'm still not sure if it's possible to make the add_shapes faster, and how to show the circles with different colors in one call.

Please note that I made other changes to the UI, using a new Combo_box class, mainly because I am testing (still conceiving) a modular way to implement new SIM modalities. Hope this is not causing visualization issues, particularly on Mac.

**Comment by pptman** [comment] 2022-05-24 11:20
You can show multiple ellipses with different colours in one call by passing the colours in a list.  I have implemented this in the latest commit with changes to show_eta(), show_carrier() and add_circles().  I don't notice a massive speed up though.  However, I did notice that editing the circles in the Napari UI itself is very fast so maybe there is a way to do this quicker.

Incidentally I get a lot of Warnings about 'element wise comparison failed' from numpy from deep inside the add_circles routines.  It only seems to happen on newly created shapes layers.  I tried doing things like sending the ellipses as a ndarray instead of as a list of np.arrays but this has not got rid of the warning.  I think that the list of np.arrays is the correct thing by the way, but that doesn't fix the problem either, but I have added it in a separate commit.

The combo-box is fine.  It only has 2 entries, is this correct?  By the way switching the accel combo-box seems to delete a bunch of the layers (xcorr, eta I noticed),and now I see that this is caused by calling reset_processor.  I'm not sure that this is necessary.   Internally the processor stores everything as numpy arrays and only transfers things to the GPU when doing any calculations so it should be safe to leave these layers visible.  So you can switch processing methods without resetting or recalibrating.  I will leave you to change this in case you have a reason to leave it as is.

**Comment by andreabassi78** [comment] 2022-05-24 22:13
Nice improvement in the show functions. Let's see if we understand how to make it as fast as in a direct call from the napari viewer.

I don't see these Warning. However, in the past I had some strange warnings using the threadworker, which disappeared with a newer version of napari. 
This is the reason why [I added this and similar lines](https://github.com/andreabassi78/napari-sim-processor/blob/8b1590d0c0a0d4c492f517a8a5936fbbe6a8a16f/src/napari_sim_processor/_sim_widget.py#L840)
I know it's very rude, but ignoring the warnings would fix the problem, for now. We could otherwise report this as an issue in napari.

I was a bit conservative in implementing the self.proc Combo_box. In the last commit I  changed its write_function to self.setReconstructor instead of self.start_sim_processor (that resets the processor). I'm going to release a new version of the code, so that me and @micropolimi can test it further.

**Comment by andreabassi78** [comment] 2022-05-24 22:16
BTW, yes the Sim_mode combobox has only 2 entries, because I am not using the simProcessor anymore. I assume it's a particular case of the convSimProcessor, but correct me if I'm wrong.

**Comment by pptman** [comment] 2022-05-24 23:12
Yes I realised that about the Sim_mode combo-box shortly after I wrote my comment!  It is perfectly reasonable to use convSimProcessor instead of simProcessor for 1x3 sim.  Their behaviour will be identical.  We should leave simProcessor in there though as the matrix construction is easier to understand.

As far as warnings are concerned we can probably not do much about those in Napari, but if they happen in our code it would be good to fix them.

For the record, the specific warning that I get (on both mac and windows running python 3.9 and numpy 1.22.0 or 1.22.2) is:
```
/usr/local/lib/python3.9/site-packages/numpy/core/numeric.py:2449: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison!
```
If you look up this warning on google there is quite a bit of discussion about the fact that this is an incompatibility between the way numpy does things and the way python does things that is as yet unresolved!

**Comment by andreabassi78** [comment] 2022-05-29 20:05
I noticed that creating and updating a Shapes layer takes much longer than creating and updating a Labels layer. I just asked for confirmation on [imagesc](https://forum.image.sc/t/fastest-way-to-annotate-image/67653). It holds for small images, but also for large ones (at least up to 2000X2000 px)
If there are no better ways to update the Shapes I would go for substituting the circles with labels as in the [example here](https://github.com/andreabassi78/napari-sim-processor/blob/cb1fd883722aeef895f38bb9283cc1346f701b8a/src/napari_sim_processor/temp.py#L29).

This would make the update faster and reduce the lag to a minimum, when play is selected.

**Comment by andreabassi78** [comment] 2022-06-17 16:10
I added [a method](https://github.com/andreabassi78/napari-sim-processor/blob/53cef9de7455df0fe42c3a598954a4d732069b35/src/napari_sim_processor/_sim_widget.py#L345) to avoid update of xcorr, etacircle and carriers when only the phase step changes.  Everything works smoothly in my Windows PCs.
I think that this is the best we can do given the napari shapes update time. I will close the issue after further testing on Linux.

**Comment by andreabassi78** [comment] 2022-07-07 14:14
It looks fast (as possible) in Ubuntu too. I close the issue

**Closed by andreabassi78** 2022-07-07 14:14 UTC
Labels: useability
